blog/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'contacts' => 'contacts#new'

  resource :contacts, only: [:new,:create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
class Article < ApplicationRecord
end

blog/app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
  end

  def create
    render plain: params[:article].inspect
  end
end

blog/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new

  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email,:message)
  end

end

blog/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/contacts_helper.rb
module ContactsHelper
end

blog/app/helpers/home_helper.rb
module HomeHelper
end

blog/app/views/articles/index.html.erb
<h1>New article!</h1>

<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %> <br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %> <br/>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

blog/app/views/contacts/create.html.erb
<p>Thanks!</p>

blog/app/views/contacts/new.html.erb
<h1>Contact us</h1>

<%= form_for :contact, url: contacts_path do |f| %>
  <% if @contact && @contact.errors.any? %>
  <p>
      <ul>
      <%= @contact.errors.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
      </ul>
  </p>
  <% end %>

  <p>
    <%= f.label :email %> <br/>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :message %> <br/>
    <%= f.text_area :message %>
  </p>

  <p>
    <%= f.submit 'Add contact' %>
  </p>
<% end %>

blog/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>